config/routes.rb
Rails.application.routes.draw do
  resources :games
  get '/rankings', to: 'pages#rankings'
  get '/elo', to: 'pages#elo'
  get '/feed', to: 'pages#feed'
  get '/faq', to: 'pages#faq'
  get '/news', to: 'pages#news'
  root 'pages#rankings'

  devise_for :users
  resources :users, only: [:show]

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :games
      resources :players
    end
  end
end

app/views/partials/_badges.html.erb
<div class="columns is-hidden-mobile">
  <div class="column is-2 is-offset-3">
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content center-text">
            <p>
              <strong>Win %</strong>
              <br>
              <small><%= @user_high_perc.username %></small>
            </p>
          </div>
        </div>
      </article>
    </div>
  </div>
  <div class="column is-2">
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content center-text">
            <p>
              <strong>No Study</strong>
              <br>
               <small><%= @user_most_games.username %></small>
            </p>
          </div>
        </div>
      </article>
    </div>
  </div>
  <div class="column is-2">
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content center-text">
            <p>
              <strong>No GG</strong>
              <br>
              <small><%= @user_most_losses.username %></small>
            </p>
          </div>
        </div>
      </article>
    </div>
  </div>
</div>
<div class="columns is-hidden-mobile">
  <div class="column is-2 is-offset-3">
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content center-text">
            <p>
              <strong>Variety</strong>
              <br>
              <small><%= @user_most_opp.username %></small>
            </p>
          </div>
        </div>
      </article>
    </div>
  </div>
  <div class="column is-2 ">
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content center-text">
            <p>
              <strong>FUDGER</strong>
              <br>
              <small>Divichi</small>
            </p>
          </div>
        </div>
      </article>
    </div>
  </div>
  <div class="column is-2 ">
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content center-text">
            <p>
              <strong>AFK</strong>
              <br>
              <small><%= @user_afk.username %></small>
            </p>
          </div>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/partials/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p>
        <strong>CFA Pong</strong> by <a href="https://github.com/savsaville">SavSaville</a>, <a href="https://github.com/marlbones">Marlbones</a> and <a href="https://github.com/BinnyK">BinnyK</a>. 
      </p>
      <p>
        Source code
      </p>
      <p>
        <a class="icon" href="https://github.com/BinnyK/dynamic-pilgrim">
          <i class="fa fa-github"></i>
        </a>
      </p>
    </div>
  </div>
</footer>

app/views/partials/_nav.html.erb
<nav class="nav has-shadow">
  <div class="container">
    <div class="nav-left">
      <a href="/" class="nav-item">
        <img src="<%= asset_path("cfapongbat.png" ) %>" />
      </a>
      <!-- <a class="nav-item is-tab is-hidden-mobile is-active">Rankings</a> -->
      <%= link_to "Rankings", root_path, class: "nav-item is-tab is-hidden-mobile"%>
<<<<<<< HEAD
      <!-- <%= link_to "ELO", pages_ELO_path, class: "nav-item is-tab is-hidden-mobile"%> -->
      <%= link_to "Feed", pages_feed_path, class: "nav-item is-tab is-hidden-mobile"%>
      <%= link_to "FAQ", pages_faq_path, class: "nav-item is-tab is-hidden-mobile "%>
      <%= link_to "News", pages_news_path, class: "nav-item is-tab is-hidden-mobile "%>
=======
      <%= link_to "Feed", feed_path, class: "nav-item is-tab is-hidden-mobile"%>
      <%= link_to "FAQ", faq_path, class: "nav-item is-tab is-hidden-mobile "%>
      <%= link_to "News", news_path, class: "nav-item is-tab is-hidden-mobile "%>
>>>>>>> upstream/master
    </div>
    <span id="nav-toggle" class="nav-toggle">
      <span></span>
      <span></span>
      <span></span>
    </span>
    <div id='nav-menu' class="nav-right nav-menu">
      <!-- <a class="nav-item is-tab is-hidden-tablet">Rankings</a> -->
      <!-- <a class="nav-item is-tab">
        <!-- THIS IS WHERE THE AVATAR WILL GO -->
        <!-- <figure class="image is-16x16" style="margin-right: 8px;">
          <img src="http://bulma.io/images/jgthms.png">
        </figure>
        Profile
      </a> -->
      <%= link_to "Feed", feed_path, class: "nav-item is-tab is-hidden-desktop is-hidden-tablet"%>
      <%= link_to "FAQ", faq_path, class: "nav-item is-tab is-hidden-desktop is-hidden-tablet "%>
      <%= link_to "News", news_path, class: "nav-item is-tab is-hidden-desktop is-hidden-tablet "%>

      <% if user_signed_in? %>
        <%= link_to 'Profile', current_user, class: "nav-item is-tab"  %>
        <%= link_to 'Edit Account', edit_user_registration_path, class: "nav-item is-tab"  %>
        <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: "nav-item is-tab" %>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: "nav-item is-tab"  %>
      <% end %>
    </div>
  </div>
</nav>