config/routes.rb
Rails.application.routes.draw do
  resources :games
  get '/rankings', to: 'pages#rankings'
  get '/elo', to: 'pages#elo'
  get '/feed', to: 'pages#feed'
  get '/faq', to: 'pages#faq'
  get '/news', to: 'pages#news'
  root 'pages#rankings'

  devise_for :users
  resources :users, only: [:show]

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :games
      resources :players
    end
  end
end

app/views/pages/ELO.html.erb
<%#= image_tag(asset_path("tt1.png")) %>
<img src="<%= asset_path("cfaponglogo.png" ) %>" class="logo-banner" />
<h1 class="title is-1 has-text-centered">Rankings</h1>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <p class="has-text-centered"><%= link_to "Enter results", new_game_path, class:"button is-primary" %></p>
  <% end %>
<% end %>

<div class="columns">
  <div class="column is-8 is-offset-2">
    <div class="table-box">
      <table class="table">
        <thead>
          <tr>
            <th><abbr title="Position">Pos</abbr></th>
            <th>Name</th>
            <th><abbr title="Won">W</abbr></th>
            <th><abbr title="Lost">L</abbr></th>
            <th><abbr title="Points">Pts</abbr></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each_with_index do |user, index|%>
            <tr>
              <th><%= index + 1 %></th>
              <td><%= user.username %></td>
              <td><%= user.wins %></td>
              <td><%= user.losses %></td>
              <td><%= user.elo %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/pages/elo.html.erb
<%#= image_tag(asset_path("tt1.png")) %>
<img src="<%= asset_path("cfaponglogo.png" ) %>" class="logo-banner" />
<h1 class="title is-1 has-text-centered main-title">Rankings</h1>

<%= render 'partials/badges' %>

<% if user_signed_in? %>
  <% if current_user.admin? %>
    <p class="has-text-centered"><%= link_to "Enter results", new_game_path, class:"button is-primary" %></p>
  <% end %>
<% end %>

<div class="columns">
  <div class="column is-8 is-offset-2">
    <div class="table-box">
      <table class="table">
        <thead>
          <tr>
            <th><abbr title="Position">Pos</abbr></th>
            <th>Name</th>
            <th><abbr title="Won">W</abbr></th>
            <th><abbr title="Lost">L</abbr></th>
            <th><abbr title="Points">ELO</abbr></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each_with_index do |user, index|%>
            <tr>
              <th><%= index + 1 %></th>
              <td><%= link_to user.username, user %></td>
              <td><%= user.wins %></td>
              <td><%= user.losses %></td>
              <td><%= user.elo %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/pages/faq.html.erb
<section class="section">
	<div class="columns">
	  <div class="column is-8 is-offset-2">

			<h1 class="title is-1">FAQ page</h1>

			<h1 class="title is-3">1. How does the point system work?</h1>

			<p class="title is-5">Rank difference is <span class="highlight-blue">2 or less</span> (e.g. 1 & 2 or 1 & 3)</p>
			<ul class="faqlist">
				<li>Higher rank wins = <span class="highlight-green">+2 points</span></li>
				<li>Lower rank wins = <span class="highlight-green">+3 points</span></li>
				<li>Higher rank loses = <span class="highlight-red">-2 points</span></li>
				<li>Lower rank loses = <span class="highlight-red">-1 points</span></li>
			</ul>
			<br>

			<p class="title is-5">Rank difference is <span class="highlight-blue">3 or more</span> (e.g. 1 & 4 or 3 & 8)</p>
			<ul>
				<li>Higher rank wins = <span class="highlight-green">+1 points</span></li>
				<li>Lower rank wins = <span class="highlight-green">+5 points</span></li>
				<li>Higher rank loses = <span class="highlight-red">-5 points</span></li>
				<li>Lower rank loses = <span class="highlight-red">-0 points</span></li>
			</ul>
			<br>
			<h1 class="title is-3">2. How do the games work?</h1>
			<ul class="faqlist">
				<li>Please inform an Admin after completing a match, (Marlon, Binny or Sav)</li>
				<li>All games are best of 5 sets, (first to 3)</li>
				<li>All sets are first to 5 points, (player must win set by 2)</li>
				<li>Player can only win points on own serve.</li>
				<li>To start the match, the lowest rank player serves</li>
				<li>After that, winner of the point maintains service</li>
				<li>Server can serve to any part of the oppostion half, providing they hit from behind the table</li>
				<li>The loser of the previous set serves to start a new set</li>
				<li>If the ball hits the net and goes over on a serve, it is a let</li>
				<li>Three lets in a row is a loss of service</li>
				<li>Players swap ends after each set</li>
				<li>Player of a higher rank must accept a challenge from a lower ranked player, (maximum 1 challenge a day)</li>
				<li>Players must shake hands and congratulate each other on a good game after each match</li>

			</ul>


		</div>
	</div>
</section>

app/views/pages/feed.html.erb
<%#= image_tag(asset_path("tt1.png")) %>
<img src="<%= asset_path("cfaponglogo.png" ) %>" class="logo-banner" />
<h1 class="title is-1 has-text-centered">Latest Results</h1>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <p class="has-text-centered"><%= link_to "Enter results", new_game_path, class:"button is-primary" %></p>
  <% end %>
<% end %>

<%= search_form_for @search, url: feed_path do |f| %>
  <div class="field has-text-centered">
    <%#= f.label :winner_name_or_loser_name_cont, "Search for Something" %>
    <%= f.text_field :winner_name_or_loser_name_cont %>
  </div>
  <div class="actions has-text-centered"><%= f.submit "Search", class:"button is-primary" %></div>
<% end %>


<div class="columns">
  <div class="column is-8 is-offset-2">
    <div class="table-box">
      <table class="table">
        <thead>
          <tr>
            <th>Win</th>
            <th>Score</th>
            <th>Lost</th>
            <th>Score</th>
            <th>Date</th>
          </tr>
        </thead>

        <tbody>
          <% @games.each do |game|%>
            <tr>
              <td><%= game.winner_name %></td>
              <td><%= game.winner_score %></td>
              <td><%= game.loser_name %></td>
              <td><%= game.loser_score %></td>
              <td><%= time_ago_in_words(game.created_at) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/pages/news.html.erb
<section class="section">
	<div class="columns">
	  <div class="column is-8 is-offset-2">

			<h1 class="title is-1">News</h1>

			<h1 class="title is-3">Dynamic Pilgrim Launches</h1>
      <p class="title is-6">Monday 8th of May 2017 </p>

			<p class="title is-5">Dynamic Pilgrim has finally launched! Sign-up and report to Sav, Binny or Marlon when you want to register an official match!</p>
			<p class="title is-5">More exciting updates and features coming shortly!</p>

		</div>
	</div>
</section>

app/views/pages/rankings.html.erb
<%#= image_tag(asset_path("tt1.png")) %>
<img src="<%= asset_path("cfaponglogo.png" ) %>" class="logo-banner" />
<h1 class="title is-1 has-text-centered main-title">Rankings</h1>

<%= render 'partials/badges' %>

<% if user_signed_in? %>
  <% if current_user.admin? %>
    <p class="has-text-centered"><%= link_to "Enter results", new_game_path, class:"button is-primary" %></p>
  <% end %>
<% end %>

<div class="columns">
  <div class="column is-8 is-offset-2">
    <div class="table-box">
      <table class="table">
        <thead>
          <tr>
            <th><abbr title="Position">Pos</abbr></th>
            <th>Name</th>
            <th><abbr title="Won">W</abbr></th>
            <th><abbr title="Lost">L</abbr></th>
            <th><abbr title="Points">Pts</abbr></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each_with_index do |user, index|%>
            <tr>
              <th><%= index + 1 %></th>
              <td><%= link_to user.username, user %></td>
              <td><%= user.wins %></td>
              <td><%= user.losses %></td>
              <td><%= user.points %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>